class FileName:
    GOOGLE_CREDENTIALS = 'credentials.json'
    INFO_JSON = 'info.jsonc'
    PASSED_JSON = 'passed.jsonc'
    

class TemplateLinks:
    GUILD = "https://discord.new/RVh3qBrGcsxA"
    ENROLMENT_SHEET = "1HzCwb68D3L2sC4WFEBYajz4co5sQvtgSpp2fIf8aMqc"
    MARKS_SHEET = "1wfamZfPPXvYxHegBEngxonPtBmJBiFT5D0WAvwLchY0"
    

class RegexPattern:
    # course details
    COURSE_CODE = r"CSE[0-9]{3}"
    COURSE_NAME = r"(?!<).+"
    SEMESTER = r"(Fall|Spring|Summer) 20[0-9]{2}"
    # marks group (with space)
    MARKS_GROUPS = r"^\[\s*(\s*(\s*\[\s*([1-9][0-9]*\s*,\s*)*[1-9][0-9]*\s*\]\s*,\s*)*\[\s*([1-9][0-9]*\s*,\s*)*[1-9][0-9]*\s*\]\s*)?\]$"
    # student details
    STUDENT_ID = r"[0-9]{8}"
    NICK_NAME = r"\[[0-9]{8}\].*"
    # faculty details
    INITIAL = r"^\[([A-Z0-9]{3,4})\].*"
    # google drive file/folder id
    r"(?<=/)[\w_-]{15,}|^[\w_-]{15,}"
    
    
class InfoField:
    COURSE_CODE = "course_code"
    COURSE_NAME = "course_name"
    SEMESTER = "semester"
    SECTION_COUNT = "n_sections"
    MISSING_SECTIONS = "missing_sections"
    # tokens and ids
    ROUTINE_SHEET_ID = "routine_sheet_id"
    GUILD_ID = "guild_id"
    BOT_TOKEN = "bot_token"
    # autogenerated fields
    MARKS_GROUPS = "marks_groups"
    INVITE_LINK = "invite"
    ENROLMENT_SHEET_ID = "enrolment"
    MARKS_SHEET_IDS = "marks"
    BUTTONS = "buttons"
    
# TODO: make it into class?
info_row_dict = {'Helper Text': 4, 'Parent Column': 9, 'Self Column': 14, 'Depth': 23,
                 'Total Marks': 5, 'Publish?': 1, 'Actual Marks?': 22, 'Children Columns': 17}