class InfoField:
    COURSE_CODE = "course_code"
    COURSE_NAME = "course_name"
    SEMESTER = "semester"
    NUM_SECTIONS = "n_sections"
    MISSING_SECTIONS = "missing_sections"
    # tokens and ids
    ROUTINE_SHEET_ID = "routine_sheet_id"
    MARKS_FOLDER_ID = "enrolment_and_marks_folder_id"
    GUILD_ID = "guild_id"
    BOT_TOKEN = "bot_token"
    # autogenerated fields
    MARKS_GROUPS = "marks_groups"
    INVITE_LINK = "invite"
    ENROLMENT_SHEET_ID = "enrolment"
    MARKS_SHEET_IDS = "marks"
    BUTTONS = "buttons"


class FileName:
    GOOGLE_CREDENTIALS = 'credentials.json'
    SHEETS_CREDENTIALS = 'sheets.googleapis.com-python.json'
    INFO_JSON = 'info.jsonc'
    VALID_JSON = 'valid_info.jsonc'
    COMMANDS_FOLDER = 'bot_commands'
    MARKS_SHEET_TITLE = '{course_code}-{sections} Marks Gradesheet {semester}'
    ENROLMENT_SHEET_TITLE = '{course_code} {semester} Enrolment Manager'
    SEC_MARKS_WORKSHEET = 'Sec {sec:02d}'


class TemplateLinks:
    GUILD = "https://discord.new/RVh3qBrGcsxA"
    ENROLMENT_SHEET = "1HzCwb68D3L2sC4WFEBYajz4co5sQvtgSpp2fIf8aMqc"
    MARKS_SHEET = "1wfamZfPPXvYxHegBEngxonPtBmJBiFT5D0WAvwLchY0"
    

class RegexPattern:
    # course details
    COURSE_CODE = r"CSE[0-9]{3}"
    COURSE_NAME = r"(?!<).+"
    SEMESTER = r"(Fall|Spring|Summer) 20[0-9]{2}"
    # student details
    STUDENT_ID = r"[0-9]{8}"
    STUDENT_NICKNAME = r"\[[0-9]{8}\].+"
    # faculty details
    FACULTY_NICKNAME = r"^\[([A-Z0-9]{3,4})\].+"
    # google drive file/folder id
    GOOGLE_DRIVE_LINK_ID = r"(?<=/)[\w_-]{15,}|^[\w_-]{15,}"
    # discord id
    DISCORD_ID = r"[0-9]{17,19}"
    DISCORD_BOT_TOKEN = r"[\w-]{24}\.[\w-]{6}\.[\w-]{38}"
    
    
class SheetCellToFieldDict:
    ENROLMENT = {
        "Course Info": {
            'B2': InfoField.COURSE_CODE,
            'B3': InfoField.COURSE_NAME,
            'B6': InfoField.SEMESTER,
            'B4': InfoField.NUM_SECTIONS,
            'B5': InfoField.MISSING_SECTIONS,
            'B16': InfoField.ROUTINE_SHEET_ID
        }
    }
    MARKS = {
        "Meta": {
            'K2': InfoField.ENROLMENT_SHEET_ID
        }
    }
    

class PullMarksGroupsFrom:
    WRKSHT = 'Routine'
    CELL = 'L2'
    
    
# TODO: make it into class?
info_row_dict = {'Helper Text': 4, 'Parent Column': 9, 'Self Column': 14, 'Depth': 23,
                 'Total Marks': 5, 'Publish?': 1, 'Actual Marks?': 22, 'Children Columns': 17}